package cuentas;

import java.sql.PreparedStatement;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author AndresG-8
 */
//Hereda el JFrame
public class JFrameCuenta extends javax.swing.JFrame {
    //Instancia un objeto de la clase Conexion
    Conexion con;      
    //Instancia un objeto de la clase DefaultTableModel para el uso de la tabla 
    DefaultTableModel m1;
    //se instancia un codigo tipo string para ...
    String codigo;
    /**
     * Create a new form JFrameCuenta
     */
    public JFrameCuenta() {
        initComponents();
        setLocationRelativeTo(null);
        //cuando inicia el programa se crea el objeto conexion y se almacena en la instancia creada anteriormente
        //de esta manera quedaremos con la conexion en esta clase y la podremos usar
        con = new Conexion();
        //Se cargan los datos que hayan en la base de datos
        cargarTabla();
        //es para verificar el ancho de las celdas en la tabla y ajustarlos
        formato_ancho();
        //se le da el foco al buscador y se deshabilitan los cuadros de texto
        txtBuscar.requestFocus();
        txtUrl.setEditable(false);
        txtUsuario.setEditable(false);
        txtPsw.setEditable(false);
        //se pone la URI al label (Solo informativo)
        lblBD.setText("BD: " + con.getUri());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtBuscar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtUrl = new javax.swing.JTextField();
        txtUsuario = new javax.swing.JTextField();
        txtPsw = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblBD = new javax.swing.JLabel();
        btnNuevo = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cuentas");
        setResizable(false);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setFocusable(false);
        jScrollPane1.setViewportView(jTable1);

        txtBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtBuscarMouseClicked(evt);
            }
        });
        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });

        jLabel1.setText("URL");

        jLabel2.setText("USUARIO");

        jLabel3.setText("CONTRASEÑA");

        txtUrl.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUrlKeyTyped(evt);
            }
        });

        txtUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUsuarioKeyTyped(evt);
            }
        });

        txtPsw.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPswKeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel4.setText("Cuentas");

        jLabel5.setText("Buscar");

        lblBD.setText("BD:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblBD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtUrl, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPsw, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtUrl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPsw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(lblBD))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/add.png"))); // NOI18N
        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        btnNuevo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                btnNuevoKeyTyped(evt);
            }
        });

        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/pencil.png"))); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        btnModificar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                btnModificarKeyTyped(evt);
            }
        });

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/delete.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        btnEliminar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                btnEliminarKeyTyped(evt);
            }
        });

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cancel.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        btnSalir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                btnSalirKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(btnModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        switch (btnNuevo.getText()) {
            case "Nuevo":
                btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/accept.png")));             
                nuevo();
                break;
            case "Guardar":
                if(!"".equals(txtUrl.getText()) && !"".equals(txtUsuario.getText()) && !"".equals(txtPsw.getText())){
                    guardar();
                    cargarTabla();
                    formato_ancho();
                    btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/add.png")));
                    break;
                }else{
                    JOptionPane.showMessageDialog(this, "Todos los datos son obligatorios");
                }
        }
        
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        switch(btnModificar.getText()){
            case "Modificar":
                int fil_sel = jTable1.getSelectedRow();
                try {
                    String url, usuario, psw;
                    if(fil_sel == -1){
                        JOptionPane.showMessageDialog(this, "Seleccione el usuario a modificar");
                    }else{
                        //se recuperan los valores de la tabla luego de seleccionarlos
                        m1 = (DefaultTableModel) jTable1.getModel();
                        codigo = (jTable1.getValueAt(fil_sel, 0).toString());
                        url = (jTable1.getValueAt(fil_sel, 1).toString());
                        usuario = (jTable1.getValueAt(fil_sel, 2).toString());
                        psw = (jTable1.getValueAt(fil_sel, 3).toString());
                        //luego de tenerlos se los mandamos a los txt y el id se queda ahi donde esta
                        txtUrl.setText(url);
                        txtUrl.requestFocus();
                        txtUsuario.setText(usuario);
                        txtPsw.setText(psw);
                        nuevo_mod();
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                }
                break;
            case "Guardar":
                try {
                    Usuario user = new Usuario();
                    user.setId(Integer.parseInt(codigo));
                    user.setUrl(txtUrl.getText());
                    user.setUsuario(txtUsuario.getText());
                    user.setPsw(txtPsw.getText());
                    if(con.modificar(user)){
                        JOptionPane.showMessageDialog(this, "¡Usuario modificado con exito!");
                        btnModificar.setText("Modificar");
                        cargarTabla();
                        formato_ancho();
                        cancelarModificar();
                    }else{
                        JOptionPane.showMessageDialog(this, "¡Error al modificar el usuario!"); 
                    }

                }catch(Exception e){
                    e.printStackTrace();
                }
                break;
        }
        
        
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int fil_sel = jTable1.getSelectedRow();
        try {
            if(fil_sel == -1){
                JOptionPane.showMessageDialog(this, "Seleccione el usuario a eliminar", "Advertencia", JOptionPane.WARNING_MESSAGE);
            }else{
                if(JOptionPane.showConfirmDialog(this, "¿Esta seguro que desea eliminar este usuario?", "Eliminar", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE) == 0){
                    m1 = (DefaultTableModel) jTable1.getModel();
                    codigo = (jTable1.getValueAt(fil_sel, 0)).toString();
                    Usuario usuario = new Usuario();
                    usuario.setId(Integer.parseInt(codigo));
                    if(con.eliminar(usuario)){
                        JOptionPane.showMessageDialog(this, "¡Usuario eliminado con exito!");
                        cargarTabla();
                        formato_ancho();
                    }else{
                        JOptionPane.showMessageDialog(this, "¡Error al eliminar el usuario!"); 
                    }
                }
            }
        }catch(Exception e){
            e.printStackTrace();
        }    
       
    }//GEN-LAST:event_btnEliminarActionPerformed
    
    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        switch(btnSalir.getText()){
            case "Salir":
                if(JOptionPane.showConfirmDialog(this, "¿Esta seguro que desea salir?", "Salir" , JOptionPane.YES_NO_OPTION ,JOptionPane.QUESTION_MESSAGE) == 0){
                    if(con.getConnection() != null){
                        //con.conn.close();
                        con.desconectar();
                        System.exit(0);
                        dispose();
                    }
                }
                break;
            case "Cancelar":
                cancelarNuevo();
                break;
            case "Cancelar.":
                cancelarModificar();
                break;
        }        
    }//GEN-LAST:event_btnSalirActionPerformed

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
        if(!"".equalsIgnoreCase(txtBuscar.getText())){
            buscar("SELECT id, url, usuario, password FROM Account WHERE id || url || usuario LIKE ('%"+ txtBuscar.getText() +"%')");
            formato_ancho();
        }else{
            cargarTabla();
            formato_ancho();
        }
    }//GEN-LAST:event_txtBuscarKeyReleased

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        //NADA
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void txtBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBuscarMouseClicked
        txtBuscar.setText("");
    }//GEN-LAST:event_txtBuscarMouseClicked

    private void txtUrlKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUrlKeyTyped
        char caracter = evt.getKeyChar();
        int numero = (int)(caracter);
        if(numero == 10){
            txtUsuario.requestFocus();
        }
    }//GEN-LAST:event_txtUrlKeyTyped

    private void txtUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuarioKeyTyped
        char caracter = evt.getKeyChar();
        int numero = (int)(caracter);
        if(numero == 10){
            txtPsw.requestFocus();
        }
    }//GEN-LAST:event_txtUsuarioKeyTyped

    private void txtPswKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPswKeyTyped
        char caracter = evt.getKeyChar();
        int numero = (int)(caracter);
        if(numero == 10){
            btnNuevo.requestFocus();
        }
    }//GEN-LAST:event_txtPswKeyTyped

    private void btnNuevoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnNuevoKeyTyped
        char caracter = evt.getKeyChar();
        int numero = (int)(caracter);
        if(numero == 10){
            btnNuevo.doClick();
        }
    }//GEN-LAST:event_btnNuevoKeyTyped

    private void btnModificarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnModificarKeyTyped
        char caracter = evt.getKeyChar();
        int numero = (int)(caracter);
        if(numero == 10){
            btnModificar.doClick();
        }
    }//GEN-LAST:event_btnModificarKeyTyped

    private void btnEliminarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnEliminarKeyTyped
        char caracter = evt.getKeyChar();
        int numero = (int)(caracter);
        if(numero == 10){
            btnEliminar.doClick();
        }
    }//GEN-LAST:event_btnEliminarKeyTyped

    private void btnSalirKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnSalirKeyTyped
        char caracter = evt.getKeyChar();
        int numero = (int)(caracter);
        if(numero == 10){
            btnSalir.doClick();
        }
    }//GEN-LAST:event_btnSalirKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameCuenta().setVisible(true);
            }
        });
    }

    private void cargarTabla(){
        //se verifica que la conexión este abierta y se procede con la consulta de datos y cargado de la tabla
        if(con.getConnection() != null){
            try{
                String sql = "select * from Account";
                //con.st = con.conn.createStatement();
                con.st = con.getConnection().createStatement();
                con.rs = con.st.executeQuery(sql);
                try{
                    m1 = (DefaultTableModel)jTable1.getModel();
                    m1.setRowCount(0);
                    ResultSetMetaData metaDatos = con.rs.getMetaData();//aca van los agregados para consultar los titulos
                    // Se obtiene el numero de columnas.
                    int numeroColumnas = metaDatos.getColumnCount();
                    // Se obtienen las etiquetas para cada columna
                    Object[] etiquetas = new Object[numeroColumnas];
                    for (int i = 0; i < numeroColumnas; i++){
                             etiquetas[i] = metaDatos.getColumnLabel(i + 1);
                    }
                    // Se meten las etiquetas en el modelo. El numero
                    // de columnas se ajusta automáticamente.
                    m1.setColumnIdentifiers(etiquetas);
                //se recorren los datos del result set y se organizan en un aray de objetos para luego pasarlo a la tabla
                while(con.rs.next()){
                    Object []fila = {con.rs.getInt(1),con.rs.getString(2),con.rs.getString(3),con.rs.getString(4)};
                    m1.addRow(fila);
                }
                }catch(SQLException ex){
                    JOptionPane.showMessageDialog(this, " problema con default" + ex);
                }
            }catch(SQLException e){
                e.printStackTrace();
            }
        }else{
            JOptionPane.showMessageDialog(this, "La conexion esta cerrada\n" + con);
        }
    }   
      
    private void nuevo(){
        //se habilitan los textos
        txtUrl.setEditable(true);
        txtUrl.requestFocus();
        txtUsuario.setEditable(true);
        txtPsw.setEditable(true);
        //se deshabilitan los botones
        btnModificar.setEnabled(false);
        btnEliminar.setEnabled(false);
        //se cambia el texto de los botones
        btnSalir.setText("Cancelar");
        btnNuevo.setText("Guardar");
    }
    
    private void nuevo_mod(){
        //se habilitan los textos
        txtUrl.setEditable(true);
        txtUrl.requestFocus();
        txtUsuario.setEditable(true);
        txtPsw.setEditable(true);
        //se deshabilitan los botones
        btnNuevo.setEnabled(false);
        btnEliminar.setEnabled(false);
        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/accept.png")));
        btnModificar.setText("Guardar");
        btnSalir.setText("Cancelar.");//por ver
    }
   
    private void cancelarNuevo() {
        txtUrl.setText("");
        txtUsuario.setText("");
        txtPsw.setText("");
        txtUrl.setEditable(false);
        txtUsuario.setEditable(false);
        txtPsw.setEditable(false);
        btnModificar.setEnabled(true);
        btnEliminar.setEnabled(true);
        btnNuevo.setText("Nuevo");
        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/add.png")));
        btnSalir.setText("Salir");
    }
    
    private void cancelarModificar() {
        txtUrl.setText("");
        txtUsuario.setText("");
        txtPsw.setText("");
        txtUrl.setEditable(false);
        txtUsuario.setEditable(false);
        txtPsw.setEditable(false);
        btnNuevo.setEnabled(true);
        btnEliminar.setEnabled(true);
        btnModificar.setText("Modificar");
        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/pencil.png")));
        btnSalir.setText("Salir");
    }
    
    private void guardar(){
        String usuario, url, psw;
        url = txtUrl.getText();
        usuario = txtUsuario.getText();
        psw = txtPsw.getText();
       
        Usuario usu = new Usuario(url, usuario, psw);
       
        String sql = "INSERT INTO Account (url, usuario, password) VALUES('" + usu.getUrl() + "', '" + usu.getUsuario()+ "' , '" + usu.getPsw() + "')";
        try{
            PreparedStatement pstm = con.getConnection().prepareStatement(sql);
            pstm.executeUpdate();
            JOptionPane.showMessageDialog(null, "Datos guardados con exito");
            cancelarNuevo();
        }catch(SQLException e1){
            e1.printStackTrace();
        }
    }
    
    private void buscar(String sql){
        if(con.getConnection() != null){
            try {
                con.st = con.getConnection().createStatement();
                con.rs = con.st.executeQuery(sql);
                //m1 = (DefaultTableModel) jTable1.getModel();
                m1.setRowCount(0);
                while(con.rs.next()){
                    Object[] fila = {con.rs.getInt(1), con.rs.getString(2), con.rs.getString(3), con.rs.getString(4)};
                    m1.addRow(fila);
                }
                con.rs.close();
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblBD;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtPsw;
    private javax.swing.JTextField txtUrl;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
    
    private void formato_ancho(){
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(30);
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(100);
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(233);
        jTable1.getColumnModel().getColumn(3).setPreferredWidth(233);
    }
}
